[package]
name = "binary-heap-sort"
version = "0.1.0"
authors = ["Arthur Asylgareev <virid.raven@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
